### PR TITLE
[Fix]: "Password Outdated" Error on Home Page

### LINKED ISSUE #62: [FIX]: Resolved “Password Outdated, Update It” Error on Home Page
## ISSUE
When an admin or seller logs in, a toast error appears on the Home page: “Password Outdated, Update It”.
## CAUSED
The cart is being dispatched for all roles, but it should only be dispatched for buyers.
## SOLUTION
Add a check to ensure the user is a buyer before dispatching the cart.
## FILES TO BE AFFECTED
Home page (src/pages/Nav.tsx)

### PR DESCRIPTION
**Pull request by Hakizimana-Clement**
#### What does this PR do?
This PR addresses the issue where a toast error message "Password Outdated, Update It" appears on the Home page when an admin or seller logs in.

#### Any background context you want to provide?
This fix is crucial to improve the user experience for admins and sellers by removing unnecessary error messages.

#### How should this be manually tested?
1. Clone the repo and cd into it
2. Checkout to **fix-password-out-dated** and **run npm install**
3. Run **npm run dev** to start the application locally
4. navigate to Home page as seller and admin and check if there's no error

#### Screenshots
Screenshot (2792)

### CODE REVIEW

**Review by GarrixA — APPROVED** [review]

File: src/components/Nav.tsx [hunk 1]
```diff
@@ -28,7 +28,9 @@ const Nav = () => {
 			if (!data) {
 				dispatch(fetchUserProfile()).unwrap();
 			}
-			dispatch(getCarts()).unwrap();
+			if (userData?.role === 'Buyer') {
```
Comment (Tuyisenge2) [inline src/components/Nav.tsx:31]: okay i test the functionality of this product and we still have this issue on product page when is an admin logged in

**Review by Tuyisenge2 — APPROVED** [review]

File: src/components/Nav.tsx (hunk 1 above)
Comment (Tuyisenge2) [inline src/components/Nav.tsx]: okay i tested the functionality of this fix and we still have this issue on product page when is an admin logged in 
Screenshot 2024-07-31 201457

**Review by Tuyisenge2 — CHANGES_REQUESTED** [review]

File: src/components/Nav.tsx (hunk 1 above)
Comment (Hakizimana-Clement) [reply src/components/Nav.tsx]: oooh, thanks. let me fix it ASAP.

**Review by kwizera-bonheur25 — APPROVED** [review]

**Review by Tuyisenge2 — APPROVED** [review]

**Review by leandreAlly — APPROVED** [review]
